### ISSUE TITLE
Libsmu Windows installer and Visual Studio Run Time

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/libsmu#72] opened 2016-05-08 17:29 UTC
While the libsmu-setup installer has a check box to optionaly install the Visual Studio runtime library ( at least I think that is what the check box is for ) it does not actually install the runtime
library, or at least all of it. I had to download vc_redist.x86.exe ( I'm running 32 bit Python ) and manually install it.

**Comment by radhermit** [comment] 2016-05-08 18:39
That's not what the checkbox is for. It's actually for installing support to build/link stuff against libsmu using VS. If you have error messages with missing dlls, please post them as most of the stuff that we can distribute legally should already be bundled.

**Comment by damercer** [comment] 2016-05-08 23:22
I'd have to uninstall the VS runtime to tell you what dll smu.exe said was missing.

**Comment by radhermit** [comment] 2016-05-09 15:28
Can you do that please? I'm unable to reproduce your issues.

**Comment by damercer** [comment] 2016-05-09 19:32
I uninstalled the VS 2015 runtime as well and everything still worked. I don't know what was going on but nothing worked right until I loaded the runtime library. Now everything is fine. My computer must have had something messed up before hand and loading the runtime stuff set it right and now all is as it should be....

**Comment by radhermit** [comment] 2016-05-10 13:05
Closing since things seem to work, please reopen if you have a reproducible issue.

**Closed by radhermit** 2016-05-10 13:05 UTC
